
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author jeremyduncan
 */
public class LanscapingGUI extends javax.swing.JFrame {

    /**
     * Creates new form LanscapingGUI
     */
    public LanscapingGUI() {
        initComponents();

        // Center the form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgYardType = new javax.swing.ButtonGroup();
        lblCompanyName = new javax.swing.JLabel();
        lblInstructions1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        rdoGrass = new javax.swing.JRadioButton();
        rdoGravel = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        mnb1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mniSubmitOrder = new javax.swing.JMenuItem();
        mniReset = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jeremy Duncan Landscapes");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(700, 344));
        setPreferredSize(new java.awt.Dimension(770, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(770, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCompanyName.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompanyName.setText("Jeremy Duncan Landscapes");
        getContentPane().add(lblCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 720, -1));

        lblInstructions1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblInstructions1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions1.setText("Would you like a grass or gravel yard?");
        getContentPane().add(lblInstructions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 87, 720, -1));

        btnReset.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 110, -1));

        btgYardType.add(rdoGrass);
        rdoGrass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rdoGrass.setText("Grass");
        rdoGrass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoGrass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGrassActionPerformed(evt);
            }
        });
        getContentPane().add(rdoGrass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 148, -1, -1));

        btgYardType.add(rdoGravel);
        rdoGravel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rdoGravel.setText("Gravel");
        rdoGravel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rdoGravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoGravelActionPerformed(evt);
            }
        });
        getContentPane().add(rdoGravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 148, -1, -1));

        btnNext.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 110, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setText("$2 per sqft");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setText("$5 per sqft");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 80, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Dirt_400.jpg"))); // NOI18N
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 160, 120));

        mnuFile.setText("File");

        mniExit.setText("Exit");
        mnuFile.add(mniExit);

        mnb1.add(mnuFile);

        mnuOrder.setText("Order");

        mniSubmitOrder.setText("Submit Order");
        mnuOrder.add(mniSubmitOrder);

        mniReset.setText("Reset");
        mnuOrder.add(mniReset);

        mnb1.add(mnuOrder);

        setJMenuBar(mnb1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // call reset method
        reset();

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
// create the second GUI form
        LanscapingGUI_Info infoForm = new LanscapingGUI_Info();

// set default close operation to "dispose" so application stays open
        infoForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

// launch the second GUI form by making it visible
        infoForm.setVisible(true);

    }//GEN-LAST:event_btnNextActionPerformed

    private void rdoGrassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGrassActionPerformed
        if (rdoGrass.isSelected()) {
            // look in directory where class exists, and get location of "grass.jpg"
            URL location = this.getClass().getResource("./imgs/grass_400.jpg");

            // create image using the location of "grass.jpg"
            ImageIcon icon = new ImageIcon(location);

            // set the image icon to the label
            lblImage.setIcon(icon);
        }

    }//GEN-LAST:event_rdoGrassActionPerformed

    private void rdoGravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoGravelActionPerformed
        if (rdoGravel.isSelected()) {
// find image, create image icon, and set image icon to label
            lblImage.setIcon(new ImageIcon(this.getClass().getResource("./imgs/dirt_400.jpg")));
        }

    }//GEN-LAST:event_rdoGravelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LanscapingGUI_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LanscapingGUI_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LanscapingGUI_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LanscapingGUI_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LanscapingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgYardType;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JMenuBar mnb1;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniReset;
    private javax.swing.JMenuItem mniSubmitOrder;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuOrder;
    private javax.swing.JRadioButton rdoGrass;
    private javax.swing.JRadioButton rdoGravel;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        // clear the radiobutton selection
        btgYardType.clearSelection();

        // put the image back to "Dirt"
        lblImage.setIcon(new ImageIcon(this.getClass().getResource("dirt.jpg")));
    }

}
